dist: bionic
language: ruby
rvm: 2.7
script: bundle exec rake test
before_install:
  - ./test/ci/install_elasticsearch.sh
cache:
  directories:
    - $HOME/elasticsearch
env:
  - ELASTICSEARCH_VERSION=6.7.0
jdk: openjdk10
notifications:
  email:
    on_success: never
    on_failure: change
